/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import java.io.IOException;
import javax.swing.JOptionPane;
import Program.*;
import java.io.Console;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author Dicas NTB
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }
    static ShowText console = new ShowText();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KCK - Odpowiadacz 4000");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        Display.setEditable(false);
        Display.setBackground(new java.awt.Color(204, 204, 204));
        Display.setColumns(20);
        Display.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Display.setLineWrap(true);
        Display.setRows(5);
        Display.setWrapStyleWord(true);
        Display.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Podgląd konsoli", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));
        Display.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(Display);
        ShowText dispconsole = new ShowText();
        console = dispconsole;
        console.setDisplay(Display);
        Display.getAccessibleContext().setAccessibleName("Projekt KCK \"Odpowiadacz 4000\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);

                console.sendMsg("Program wystartował.\n");
                String[] database = new String[1000000];
                Question q = new Question();
                Analysis a = new Analysis();
                FileMethods f = new FileMethods();
                String question = null;

                //question = "Kto zabił Kennedy'ego w Dallas?";
                //question = "Kto zabił Kennedy'ego w Los Angeles?";
                //question = "Kto zabił Narutowicza w Warszawie?";
                //question = "Kto zabił Narutowicza w Zachęcie?";
                //question = "Kto Kennedy'ego zabił w Dallas?";
                //question = "Kto w Dallas zabił Kennedy'ego?";
                //question = "Kto zamordował w Dallas Kennedy'ego?";
                //question = "Kto uśmiercił Kennedy'ego w Dallas?";
                //question = "Kto pozbawił życia Kennedy'ego w Dallas?";

                // *
                //question = "Kto zabił Kennedy'ego?";
                //question = "Kto zabił Narutowicza w Dallas?";
                //question = "Kto zabił Oswalda w Dallas?";


                //question = "Kto zabił Niewiadomskiego w Nowym Jorku?";
                //question = "Kto zabił Kennedy'ego u wybrzeża wyspy Martha's Vineyard?";
                //question = "Kto zabił Kennedy'ego w Waszyngtonie?";

                // **
                //question = "Kto zabił?";
                //question = "Kto zabił w Dallas?";

                if (question == null) {
                    question = q.AskQuestion();
                }

                if (question == null) {
                    JOptionPane.showMessageDialog(null, "Nie podano pytania. Kończenie programu.");
                    System.exit(0);
                } else {

                    while (q.QuestionAnalysis(question) == false) {
                        JOptionPane.showMessageDialog(null, "Zadano błędne pytanie. Proszę wpisz pytanie jeszcze raz.");
                        question = q.AskQuestion();
                        if (question == null) {
                            JOptionPane.showMessageDialog(null, "Nie podano pytania. Kończenie programu.");
                            System.exit(0);
                        }
                    }
                    String place = q.FindPlaceByKey(question);
                    String person = q.FindPersonByKey(question, place);
                    console.sendMsg("Słowa kluczowe:");
                    if (q.QuestionAnalysis(question) == false && question == null) {
                        JOptionPane.showMessageDialog(null, "Nie podano pytania. Kończenie programu.");
                        System.exit(0);

                    } else if (person == null) {
                        JOptionPane.showMessageDialog(null, "Nie podano nazwiska, bądź nie odnaleziono.");
                    } else {
                        console.sendMsg("| Pytanie:        " + question);
                        console.sendMsg("| Miejscowość:    " + place);
                        console.sendMsg("| Wybrano osobę:  " + person);
                        try {
                            f.ReadData(database,console);
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        console.sendMsg("Zapisano dane do bazy tymczasowej.\nAnalizowanie danych w toku...");
                        a.DataAnalysis(database, person, place,console);

                    }
                }
            }
        });



    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Display;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
